package entrez

type (
	PubMed          struct{}
	Protein         struct{}
	Nuccore         struct{}
	Nucleotide      struct{}
	Nucgss          struct{}
	Nucest          struct{}
	Structure       struct{}
	Sparcle         struct{}
	Genome          struct{}
	AnnotInfo       struct{}
	Assembly        struct{}
	BioProject      struct{}
	BioSample       struct{}
	BlastdbInfo     struct{}
	Books           struct{}
	CDD             struct{}
	ClinVar         struct{}
	Clone           struct{}
	Gap             struct{}
	GAPPlus         struct{}
	Grasp           struct{}
	DBVar           struct{}
	Gene            struct{}
	Gds             struct{}
	GeoProfiles     struct{}
	Homologene      struct{}
	MedGen          struct{}
	MESH            struct{}
	NCBISearch      struct{}
	NLMCatalog      struct{}
	OMIN            struct{}
	OrgTrack        struct{}
	PMC             struct{}
	Popset          struct{}
	Probe           struct{}
	ProteinClusters struct{}
	PCAssay         struct{}
	BioSystems      struct{}
	PCCompound      struct{}
	PCSubstance     struct{}
	PubMedHealth    struct{}
	Seqannot        struct{}
	SNP             struct{}
	SRA             struct{}
	Taxonomy        struct{}
	BioCollections  struct{}
	UniGene         struct{}
	GenColl         struct{}
	GTR             struct{}
)
